/* This file is autogenerated by u_format_table.py from u_format.csv. Do not edit directly. */

/**************************************************************************
 *
 * Copyright 2010 VMware, Inc.
 * All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sub license, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice (including the
 * next paragraph) shall be included in all copies or substantial portions
 * of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
 * IN NO EVENT SHALL VMWARE AND/OR ITS SUPPLIERS BE LIABLE FOR
 * ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 **************************************************************************/

#include "util/format/u_format.h"
#include "u_format_bptc.h"
#include "u_format_s3tc.h"
#include "u_format_rgtc.h"
#include "u_format_latc.h"
#include "u_format_etc.h"


#include "pipe/p_compiler.h"
#include "util/u_math.h"
#include "util/u_half.h"
#include "u_format.h"
#include "u_format_other.h"
#include "util/format_srgb.h"
#include "u_format_yuv.h"
#include "u_format_zs.h"
#include "u_format_pack.h"

static const struct util_format_description
util_format_descriptions[] = {
};

const struct util_format_description *
util_format_description(enum pipe_format format)
{
   if (format >= ARRAY_SIZE(util_format_descriptions))
      return NULL;

   return &util_format_descriptions[format];
}

static const struct util_format_pack_description
util_format_pack_descriptions[] = {
};

const struct util_format_pack_description *
util_format_pack_description(enum pipe_format format)
{
   if (format >= ARRAY_SIZE(util_format_pack_descriptions))
      return NULL;

   return &util_format_pack_descriptions[format];
}

static const struct util_format_unpack_description
util_format_unpack_descriptions[] = {
};

const struct util_format_unpack_description *
util_format_unpack_description(enum pipe_format format)
{
   if (format >= ARRAY_SIZE(util_format_unpack_descriptions))
      return NULL;

   return &util_format_unpack_descriptions[format];
}

static const util_format_fetch_rgba_func_ptr util_format_fetch_rgba_table[] = {
};

util_format_fetch_rgba_func_ptr
util_format_fetch_rgba_func(enum pipe_format format)
{
   if (format >= ARRAY_SIZE(util_format_fetch_rgba_table))
      return NULL;

   return util_format_fetch_rgba_table[format];
}

